const destinations = [
  {
    name: "Kerala Backwaters",
    country: "India",
    city: "Alleppey",
    description:
      "Slow houseboat travel through palm-lined canals, a perfect escape into calm waters and village life.",
    image:
      "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944",
    bestSeason: "Winter",
    budget: "₹10k-20k",
    travelDuration: "Weekend",
    travelStyle: ["Family", "Couple"],
    destinationType: "Nature",
    rating: 4.7,
    difficulty: "Easy",
    badge: "Best AI Match",
    weather: { temp: 26, condition: "Humid" },
    popularity: 88,
    tags: ["backwaters", "houseboat", "relaxing"],
    location: { lat: 9.4981, lng: 76.3388 },
    isFeatured: true,
  },
  {
    name: "Kyoto",
    country: "Japan",
    city: "Kyoto",
    description:
      "Thousands of red torii gates, ancient temples, and quiet gardens combining culture and stillness.",
    image:
      "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e",
    bestSeason: "Spring",
    budget: "₹20k-50k",
    travelDuration: "1 Week",
    travelStyle: ["Solo", "Couple", "Friends"],
    destinationType: "Heritage",
    rating: 4.8,
    difficulty: "Easy",
    badge: "Most Popular",
    weather: { temp: 18, condition: "Mild" },
    popularity: 95,
    tags: ["temples", "culture", "gardens"],
    location: { lat: 35.0116, lng: 135.7681 },
    isFeatured: true,
  },
  {
    name: "Hoi An",
    country: "Vietnam",
    city: "Hoi An",
    description:
      "Lantern-lit old-town streets with some of the best street food in Southeast Asia.",
    image:
      "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b",
    bestSeason: "Spring",
    budget: "₹10k-20k",
    travelDuration: "3 Days",
    travelStyle: ["Friends", "Couple"],
    destinationType: "Heritage",
    rating: 4.8,
    difficulty: "Easy",
    badge: "Best AI Match",
    weather: { temp: 27, condition: "Warm" },
    popularity: 90,
    tags: ["street food", "lanterns", "old town"],
    location: { lat: 15.8801, lng: 108.338 },
    isFeatured: true,
  },
  {
    name: "Swiss Alps",
    country: "Switzerland",
    city: "Zermatt",
    description:
      "Snow-capped peaks, alpine trails, and luxury mountain resorts for an unforgettable escape.",
    image:
      "https://images.unsplash.com/photo-1531366936337-7c912a4589a7",
    bestSeason: "Winter",
    budget: "₹50k+",
    travelDuration: "1 Week",
    travelStyle: ["Couple", "Business"],
    destinationType: "Mountain",
    rating: 4.9,
    difficulty: "Challenging",
    badge: "Luxury Pick",
    weather: { temp: -2, condition: "Snowy" },
    popularity: 85,
    tags: ["skiing", "mountains", "luxury"],
    location: { lat: 46.0207, lng: 7.7491 },
    isFeatured: true,
  },
  {
    name: "Costa Rica Rainforest",
    country: "Costa Rica",
    city: "Monteverde",
    description:
      "Eco-lodges nestled in cloud forests with zip-lining, wildlife spotting, and sustainable tourism.",
    image:
      "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b",
    bestSeason: "Summer",
    budget: "₹20k-50k",
    travelDuration: "1 Week",
    travelStyle: ["Solo", "Friends"],
    destinationType: "Adventure",
    rating: 4.7,
    difficulty: "Moderate",
    badge: "Eco Tourism",
    weather: { temp: 24, condition: "Humid" },
    popularity: 78,
    tags: ["rainforest", "wildlife", "eco"],
    location: { lat: 10.3, lng: -84.8 },
    isFeatured: true,
  },
  {
    name: "Goa Coast",
    country: "India",
    city: "Goa",
    description:
      "Golden beaches, laid-back shacks, and lively nightlife along India's favorite coastline.",
    image:
      "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2",
    bestSeason: "Winter",
    budget: "₹5k-10k",
    travelDuration: "Weekend",
    travelStyle: ["Friends", "Solo"],
    destinationType: "Beach",
    rating: 4.6,
    difficulty: "Easy",
    badge: "Trending",
    weather: { temp: 29, condition: "Sunny" },
    popularity: 92,
    tags: ["beach", "nightlife", "budget"],
    location: { lat: 15.2993, lng: 74.124 },
    isFeatured: true,
  },
];

const attractions = [
  {
    name: "Sunset Fort",
    category: "Historical",
    description:
      "A hilltop fort offering panoramic sunset views over the old city.",
    image:
      "https://images.unsplash.com/photo-1548013146-72479768bada",
    rating: 4.8,
    openingHours: "6:00 AM - 8:00 PM",
    isOpenNow: true,
    entryFee: "₹200",
    crowdLevel: "Less Crowded",
    aiSuggested: true,
    location: { lat: 27.1767, lng: 78.0081 },
  },
  {
    name: "Coral Bay",
    category: "Beach",
    description:
      "A calm turquoise bay popular for snorkeling and beachside dining.",
    image:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    rating: 4.9,
    openingHours: "24 hours",
    isOpenNow: true,
    entryFee: "Free",
    crowdLevel: "Moderate",
    aiSuggested: true,
    location: { lat: 15.4909, lng: 73.8278 },
  },
  {
    name: "Ridge Trail",
    category: "Adventure",
    description:
      "A scenic hiking trail through pine forests with mountain viewpoints.",
    image:
      "https://images.unsplash.com/photo-1551632811-561732d1e306",
    rating: 4.8,
    openingHours: "5:00 AM - 6:00 PM",
    isOpenNow: true,
    entryFee: "Free",
    crowdLevel: "Less Crowded",
    aiSuggested: false,
    location: { lat: 32.2432, lng: 77.1892 },
  },
  {
    name: "Taj Mahal",
    category: "Historical",
    description:
      "Iconic white marble mausoleum and UNESCO World Heritage Site.",
    image:
      "https://images.unsplash.com/photo-1564507592333-c60657eea523",
    rating: 4.9,
    openingHours: "6:00 AM - 7:00 PM",
    isOpenNow: true,
    entryFee: "₹250",
    crowdLevel: "Crowded",
    aiSuggested: true,
    location: { lat: 27.1751, lng: 78.0421 },
  },
  {
    name: "Old Town Market",
    category: "Shopping",
    description:
      "A bustling street market known for local crafts, spices, and street food.",
    image:
      "https://images.unsplash.com/photo-1555529771-7888783a18d3",
    rating: 4.5,
    openingHours: "10:00 AM - 10:00 PM",
    isOpenNow: true,
    entryFee: "Free",
    crowdLevel: "Crowded",
    aiSuggested: false,
    location: { lat: 27.18, lng: 78.02 },
  },
];

const emergencyContacts = [
  {
    type: "Police",
    name: "Agra City Police Station",
    phoneNumber: "100",
    city: "Agra",
    description: "24x7 police assistance for tourists and residents.",
    isAvailable24x7: true,
    location: { lat: 27.1767, lng: 78.0081 },
  },
  {
    type: "Hospital",
    name: "SN Medical College Hospital",
    phoneNumber: "0562-2331595",
    city: "Agra",
    description: "Multi-speciality government hospital with emergency ward.",
    isAvailable24x7: true,
    location: { lat: 27.1591, lng: 78.0025 },
  },
  {
    type: "Ambulance",
    name: "National Ambulance Service",
    phoneNumber: "108",
    city: "Agra",
    description: "Free emergency ambulance service across India.",
    isAvailable24x7: true,
    location: { lat: 27.1767, lng: 78.0081 },
  },
  {
    type: "Women Helpline",
    name: "Women Safety Helpline",
    phoneNumber: "1091",
    city: "Agra",
    description: "24x7 helpline for women's safety and assistance.",
    isAvailable24x7: true,
    location: { lat: 27.1767, lng: 78.0081 },
  },
  {
    type: "Tourist Helpline",
    name: "Incredible India Tourist Helpline",
    phoneNumber: "1363",
    city: "Agra",
    description: "Multilingual 24x7 helpline for tourists across India.",
    isAvailable24x7: true,
    location: { lat: 27.1767, lng: 78.0081 },
  },
];

module.exports = { destinations, attractions, emergencyContacts };